name: ocean_press
description: Smooth Web App Framework for easy and fast construction of Web Applications.
version: 1.0.16
homepage: https://github.com/Colossus-Services/ocean_press

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  bones_ui: ^1.1.1
    #path: ../bones_ui
  bones_ui_bootstrap: ^1.1.1
    #path: ../bones_ui_bootstrap
  swiss_knife: ^2.5.18
    #path: ../swiss_knife
  mercury_client: ^1.1.13
    #path: ../mercury_client
  dynamic_call: ^1.0.14
    #path: ../dynamic_call
  intl_messages: ^1.1.12
    #path: ../intl_messages
  social_login_web: ^1.0.2
    #path: ../social_login_web
  enum_to_string: ^1.0.9
  markdown: ^3.0.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.2
  test: ^1.15.3
