name: ocean_press
description: Smooth Web App Framework
version: 1.0.0
homepage: https://github.com/Colossus-Services/ocean_press

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  swiss_knife: ^2.3.1
    #path: ../swiss_knife
  mercury_client: ^1.1.1
    #path: ../mercury_client
  dynamic_call: ^1.0.5
    #path: ../dynamic_call
  intl_messages: ^1.1.3
    #path: ../intl_messages
  bones_ui: ^1.0.0
    #path: ../bones_ui
  social_login_web: ^1.0.0
    #path: ../social_login_web
  enum_to_string: ^1.0.8
  markdown: ^2.1.3
  highlight: ^0.5.0

dev_dependencies:
  #pedantic: ^1.8.0
  test: ^1.6.0

